"""empty message

Revision ID: 545fb6aab157
Revises: 8ff360f197db
Create Date: 2024-08-31 12:35:42.522698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545fb6aab157'
down_revision = '8ff360f197db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocked_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['jti'])
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocked_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
